package agendamiento_clinico.Gestiones;

import agendamiento_clinico.BaseDatos;
import agendamiento_clinico.DatosCombo;
import agendamiento_clinico.Grilla;
import javax.swing.JOptionPane;

public class FrmRecetas extends javax.swing.JDialog {
    private BaseDatos bd = new BaseDatos();
    private char opc = 'z';
    private Grilla grd = new Grilla();
    
    public FrmRecetas(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        if(!this.bd.hayConexion()){
            JOptionPane.showMessageDialog(null, "Error de conexión con la base de datos");
        }else{
            this.bd.cargarCombo(cboHistorial, 
                "hc.id_historial, CONCAT('ID: ', hc.id_historial, ' - Paciente: ', p.nombre, ' ', p.apellidos)", 
                "historial_clinico hc JOIN pacientes p ON hc.id_paciente = p.id_paciente ORDER BY hc.id_historial ASC");
            this.bd.cargarCombo(cboMedicamento, "id_medicamento, nombre", "medicamentos");
        }
        this.habilitarCampos(false);
        this.habilitarBotones(true);
        this.actualizarGrilla();
        this.setLocationRelativeTo(null);
    }
    
    private void habilitarCampos(boolean estado){
        this.cboHistorial.setEnabled(estado);
        this.cboMedicamento.setEnabled(estado);
        this.txtCantidad.setEnabled(estado);
        this.txtInstrucciones.setEnabled(estado);
    }

    private void habilitarBotones(boolean estado){
        this.cmdAgregar.setEnabled(estado);
        this.cmdEliminar.setEnabled(estado);
        this.cmdModificar.setEnabled(estado);
        this.cmdGuardar.setEnabled(!estado);
    }

    private void limpiarCampos(){
        this.txtCantidad.setText(null);
        this.txtInstrucciones.setText(null);
        if (this.cboHistorial.getItemCount() > 0) this.cboHistorial.setSelectedIndex(0);
        if (this.cboMedicamento.getItemCount() > 0) this.cboMedicamento.setSelectedIndex(0);
    }


    private void actualizarGrilla(){
        String campos[] = {
            "r.id_receta", 
            "CONCAT(p.nombre, ' ', p.apellidos) AS paciente", 
            "m.nombre AS medicamento", 
            "r.cantidad", 
            "r.instrucciones"
        };

        String tablas = "recetas r " +
                        "INNER JOIN historial_clinico hc ON r.id_historial = hc.id_historial " +
                        "INNER JOIN pacientes p ON hc.id_paciente = p.id_paciente " +
                        "INNER JOIN medicamentos m ON r.id_medicamento = m.id_medicamento " +
                        "ORDER BY r.id_receta ASC";

        this.grd.cargarGrilla(grdRecetas, tablas, campos);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtCantidad = new javax.swing.JTextField();
        txtBuscar = new javax.swing.JTextField();
        cmdAgregar = new javax.swing.JButton();
        cmdModificar = new javax.swing.JButton();
        cmdEliminar = new javax.swing.JButton();
        cmdGuardar = new javax.swing.JButton();
        cmdCancelar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        grdRecetas = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtInstrucciones = new javax.swing.JTextArea();
        jLabel5 = new javax.swing.JLabel();
        cboMedicamento = new javax.swing.JComboBox<>();
        cboHistorial = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Cambria", 3, 16)); // NOI18N
        jLabel1.setText("Buscar:");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(30, 640, 60, 30);

        jLabel2.setFont(new java.awt.Font("Cambria", 3, 16)); // NOI18N
        jLabel2.setText("Historial Clinico");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(30, 20, 120, 30);

        jLabel3.setFont(new java.awt.Font("Cambria", 3, 16)); // NOI18N
        jLabel3.setText("Medicamento");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(30, 80, 110, 30);

        jLabel4.setFont(new java.awt.Font("Cambria", 3, 16)); // NOI18N
        jLabel4.setText("Instrucciones");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(30, 200, 150, 30);

        txtCantidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCantidadActionPerformed(evt);
            }
        });
        jPanel1.add(txtCantidad);
        txtCantidad.setBounds(200, 140, 200, 30);

        txtBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBuscarActionPerformed(evt);
            }
        });
        txtBuscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtBuscarKeyReleased(evt);
            }
        });
        jPanel1.add(txtBuscar);
        txtBuscar.setBounds(100, 640, 760, 30);

        cmdAgregar.setText("Agregar");
        cmdAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdAgregarActionPerformed(evt);
            }
        });
        jPanel1.add(cmdAgregar);
        cmdAgregar.setBounds(40, 300, 80, 30);

        cmdModificar.setText("Modificar");
        cmdModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdModificarActionPerformed(evt);
            }
        });
        jPanel1.add(cmdModificar);
        cmdModificar.setBounds(140, 300, 85, 30);

        cmdEliminar.setText("Eliminar");
        cmdEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdEliminarActionPerformed(evt);
            }
        });
        jPanel1.add(cmdEliminar);
        cmdEliminar.setBounds(240, 300, 77, 30);

        cmdGuardar.setText("Guardar");
        cmdGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdGuardarActionPerformed(evt);
            }
        });
        jPanel1.add(cmdGuardar);
        cmdGuardar.setBounds(330, 300, 76, 30);

        cmdCancelar.setText("Cancelar");
        cmdCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdCancelarActionPerformed(evt);
            }
        });
        jPanel1.add(cmdCancelar);
        cmdCancelar.setBounds(420, 300, 90, 30);

        grdRecetas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "ID Historial", "Medicamento", "Medicamento", "Instucciones"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(grdRecetas);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(30, 350, 830, 280);

        txtInstrucciones.setColumns(20);
        txtInstrucciones.setRows(5);
        jScrollPane2.setViewportView(txtInstrucciones);

        jPanel1.add(jScrollPane2);
        jScrollPane2.setBounds(200, 200, 470, 70);

        jLabel5.setFont(new java.awt.Font("Cambria", 3, 16)); // NOI18N
        jLabel5.setText("Cantidad");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(30, 140, 90, 30);

        jPanel1.add(cboMedicamento);
        cboMedicamento.setBounds(200, 80, 520, 30);

        jPanel1.add(cboHistorial);
        cboHistorial.setBounds(200, 20, 520, 30);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 898, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 708, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtCantidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCantidadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCantidadActionPerformed

    private void txtBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBuscarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBuscarActionPerformed

    private void txtBuscarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBuscarKeyReleased
        this.grd.filtrarGrilla(grdRecetas, this.txtBuscar.getText(), 1);
    }//GEN-LAST:event_txtBuscarKeyReleased

    private void cmdAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdAgregarActionPerformed
        this.opc = 'N';
        this.habilitarCampos(true);
        this.habilitarBotones(false);
        this.cboHistorial.requestFocus();
    }//GEN-LAST:event_cmdAgregarActionPerformed

    private void cmdModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdModificarActionPerformed
        if (grdRecetas.getSelectedRow() == -1) {
            JOptionPane.showMessageDialog(this, "Por favor, seleccione una receta de la lista para modificar.", "Aviso", JOptionPane.WARNING_MESSAGE);
            return; // Detiene la ejecución si no hay nada seleccionado
        }
        
        this.opc = 'M';
        this.habilitarBotones(false);
        this.habilitarCampos(true);

        // Ya que la tabla ahora muestra el nombre del paciente, no podemos obtener el ID del historial directamente.
        // Pero no importa, porque el ComboBox de selección de historial ya tiene el ID correcto.
        // El siguiente código busca el medicamento y rellena los otros campos.
        String nombreMedicamento = this.grdRecetas.getValueAt(this.grdRecetas.getSelectedRow(), 2).toString();
        for(int i=0; i<cboMedicamento.getItemCount();i++){
            this.cboMedicamento.setSelectedIndex(i);
            if(this.cboMedicamento.getSelectedItem().toString().equals(nombreMedicamento)){
                break;
            }
        }

        this.txtCantidad.setText(this.grdRecetas.getValueAt(this.grdRecetas.getSelectedRow(), 3).toString());
        this.txtInstrucciones.setText(this.grdRecetas.getValueAt(this.grdRecetas.getSelectedRow(), 4).toString());

        this.cboHistorial.requestFocus();
    }//GEN-LAST:event_cmdModificarActionPerformed

    private void cmdEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdEliminarActionPerformed
        if (grdRecetas.getSelectedRow() == -1) {
            JOptionPane.showMessageDialog(this, 
                "Por favor, seleccione una receta de la lista para eliminar.", 
                "Aviso", 
                JOptionPane.WARNING_MESSAGE);
            return; // Detiene la ejecución
        }

        String idReceta = this.grdRecetas.getValueAt(
                this.grdRecetas.getSelectedRow(), 0).toString();

        bd.borrarRegistro("recetas", "id_receta=" + idReceta);
        this.actualizarGrilla();
    }//GEN-LAST:event_cmdEliminarActionPerformed

    private void cmdGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdGuardarActionPerformed
        DatosCombo cboH = (DatosCombo) this.cboHistorial.getSelectedItem();
        int idHistorial = cboH.getCodigo();
        DatosCombo cboM = (DatosCombo) this.cboMedicamento.getSelectedItem();
        int idMedicamento = cboM.getCodigo();

        if(this.opc == 'N'){
            String valores = idHistorial + "," + idMedicamento + ","
                + this.txtCantidad.getText() + ",'" + this.txtInstrucciones.getText() + "'";
            bd.insertarRegistro("recetas(id_historial, id_medicamento, cantidad, instrucciones)", valores);
        } else {
            String idReceta = this.grdRecetas.getValueAt(this.grdRecetas.getSelectedRow(), 0).toString();
            String campos = "id_historial=" + idHistorial +
                    ", id_medicamento=" + idMedicamento +
                    ", cantidad=" + this.txtCantidad.getText() +
                    ", instrucciones='" + this.txtInstrucciones.getText() + "'";
            bd.actualizarRegistro("recetas", campos, "id_receta=" + idReceta);
        }
        this.opc = 'z';
        this.limpiarCampos();
        this.habilitarCampos(false);
        this.habilitarBotones(true);
        this.actualizarGrilla();
    }//GEN-LAST:event_cmdGuardarActionPerformed

    private void cmdCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdCancelarActionPerformed
        this.limpiarCampos();
        this.habilitarCampos(false);
        this.habilitarBotones(true);
    }//GEN-LAST:event_cmdCancelarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmRecetas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmRecetas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmRecetas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmRecetas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                FrmRecetas dialog = new FrmRecetas(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cboHistorial;
    private javax.swing.JComboBox<String> cboMedicamento;
    private javax.swing.JButton cmdAgregar;
    private javax.swing.JButton cmdCancelar;
    private javax.swing.JButton cmdEliminar;
    private javax.swing.JButton cmdGuardar;
    private javax.swing.JButton cmdModificar;
    private javax.swing.JTable grdRecetas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField txtBuscar;
    private javax.swing.JTextField txtCantidad;
    private javax.swing.JTextArea txtInstrucciones;
    // End of variables declaration//GEN-END:variables
}
